In [1]:
import pandas as pd

# Ejercicio 1: Lectura y Verificación Estructural
# Cargamos el archivo asegurando que no se generen columnas de índices numéricas duplicadas
df_fincas = pd.read_csv('fincas_produccion_cafe.csv', index_col=False)

# Mostramos las primeras 5 filas para verificar la carga
df_fincas.head()

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
0,FIN-8001,Chinchiná,Cenicafé 1,Honey,3.0,4800.0,1500,Ninguna
1,FIN-8002,Manizales,Cenicafé 1,Natural,5.5,2500.0,1284,Rainforest Alliance
2,FIN-8003,Manizales,Cenicafé 1,Lavado Tradicional,1.5,1200.0,1959,Rainforest Alliance
3,FIN-8004,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna
4,FIN-8005,Chinchiná,Castillo,Natural,8.0,16000.0,1929,Fairtrade

In [2]:
# Ejercicio 2: Selección Unidimensional y Proyección Multivariable
# Extraemos la columna Variedad como una Serie
serie_variedad = df_fincas['Variedad']

# Obtenemos una vista de tabla con Municipio, Area_Hectareas y Kilos_Recolectados
vista_multivariable = df_fincas[['Municipio', 'Area_Hectareas', 'Kilos_Recolectados']]

# Mostramos las primeras 5 filas de la vista
vista_multivariable.head()

   Municipio  Area_Hectareas  Kilos_Recolectados
0  Chinchiná             3.0              4800.0
1  Manizales             5.5              2500.0
2  Manizales             1.5              1200.0
3  Risaralda             3.0              4800.0
4  Chinchiná             8.0             16000.0

In [3]:
# Ejercicio 3: Acceso por Etiqueta (loc)
# Consulta todos los datos del predio situado en la posición de índice 280
predio_280 = df_fincas.loc[280]
print("--- Datos del predio 280 ---")
print(predio_280)

# Ejercicio 4: Eliminación de Filas Duplicadas
# Aplicamos .drop_duplicates() para mantener la base limpia
df_fincas = df_fincas.drop_duplicates()
print("\n--- Limpieza de duplicados ---")
print(f"Total de filas únicas restantes: {len(df_fincas)}")

--- Datos del predio 280 ---
ID_Finca               FIN-8281
Municipio             Risaralda
Variedad               Colombia
Metodo_Beneficio        Natural
Area_Hectareas              5.5
Kilos_Recolectados      16000.0
Altitud_MSNM               1821
Certificacion          Orgánico
Name: 280, dtype: object

--- Limpieza de duplicados ---
Total de filas únicas restantes: 1000

In [4]:
# Ejercicio 6: Filtrado Categórico por Lista (isin)
# Seleccionamos predios cultivados en Anserma y Risaralda
fincas_anserma_risaralda = df_fincas[df_fincas['Municipio'].isin(['Anserma', 'Risaralda'])]

# Mostramos el resultado
print(f"Fincas en Anserma y Risaralda: {len(fincas_anserma_risaralda)}")
fincas_anserma_risaralda.head()

Fincas en Anserma y Risaralda: 387

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
3,FIN-8004,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna
5,FIN-8006,Risaralda,Cenicafé 1,Honey,12.0,7500.0,1652,Orgánico
6,FIN-8007,Anserma,Colombia,Honey,5.5,4800.0,1674,Rainforest Alliance
10,FIN-8011,Risaralda,Cenicafé 1,Lavado Tradicional,5.5,2500.0,1710,Orgánico
11,FIN-8012,Anserma,Geisha,Natural,12.0,16000.0,1743,Ninguna

In [5]:
# Ejercicio 7: Filtrado por Intervalo Numérico (between)
# Aislamos los lotes cuya extensión esté entre 3.0 y 8.0 hectáreas inclusive
lotes_medianos = df_fincas[df_fincas['Area_Hectareas'].between(3.0, 8.0)]

print(f"Lotes de tamaño mediano (3 a 8 ha): {len(lotes_medianos)}")
lotes_medianos.head()

Lotes de tamaño mediano (3 a 8 ha): 585

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
0,FIN-8001,Chinchiná,Cenicafé 1,Honey,3.0,4800.0,1500,Ninguna
1,FIN-8002,Manizales,Cenicafé 1,Natural,5.5,2500.0,1284,Rainforest Alliance
3,FIN-8004,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna
4,FIN-8005,Chinchiná,Castillo,Natural,8.0,16000.0,1929,Fairtrade
6,FIN-8007,Anserma,Colombia,Honey,5.5,4800.0,1674,Rainforest Alliance

In [6]:
# Ejercicio 8: Consultas Directas con .query()
# Extraemos fincas con certificación Orgánica y más de 5000 kilos recolectados
organicos_alta_produccion = df_fincas.query("Certificacion == 'Orgánico' and Kilos_Recolectados > 5000")

print(f"Fincas orgánicas de alta producción: {len(organicos_alta_produccion)}")
organicos_alta_produccion.head()

Fincas orgánicas de alta producción: 40

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
5,FIN-8006,Risaralda,Cenicafé 1,Honey,12.0,7500.0,1652,Orgánico
30,FIN-8031,Palestina,Castillo,Natural,18.5,16000.0,1838,Orgánico
34,FIN-8035,Chinchiná,Borbon Rosado,Natural,3.0,7500.0,1578,Orgánico
61,FIN-8062,Palestina,Geisha,Lavado Tradicional,1.5,11000.0,1885,Orgánico
69,FIN-8070,Palestina,Castillo,Lavado Tradicional,8.0,16000.0,1922,Orgánico

In [7]:
# Ejercicio 9: Filtrado Compuesto con Métodos de Texto
# Construimos una condición lógica múltiple
condicion_lavado = df_fincas['Metodo_Beneficio'].str.startswith('Lavado', na=False)
condicion_geisha = df_fincas['Variedad'] == 'Geisha'

# Aplicamos ambas condiciones con el operador &
lavado_geisha = df_fincas[condicion_lavado & condicion_geisha]

print(f"Fincas de variedad Geisha con método Lavado: {len(lavado_geisha)}")
lavado_geisha.head()

Fincas de variedad Geisha con método Lavado: 67

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
16,FIN-8017,Palestina,Geisha,Lavado Tradicional,3.0,4800.0,1837,Rainforest Alliance
18,FIN-8019,Manizales,Geisha,Lavado Tradicional,12.0,7500.0,1500,Fairtrade
38,FIN-8039,Anserma,Geisha,Lavado Tradicional,18.5,1200.0,1675,Rainforest Alliance
50,FIN-8051,Chinchiná,Geisha,Lavado Tradicional,3.0,7500.0,1689,Rainforest Alliance
61,FIN-8062,Palestina,Geisha,Lavado Tradicional,1.5,11000.0,1885,Orgánico

In [8]:
# Ejercicio 10: Imputación de Valores Faltantes
# Calculamos el promedio del área
promedio_area = df_fincas['Area_Hectareas'].mean()

# Rellenamos los vacíos (NaN)
df_fincas['Area_Hectareas'] = df_fincas['Area_Hectareas'].fillna(promedio_area)
df_fincas['Kilos_Recolectados'] = df_fincas['Kilos_Recolectados'].fillna(0.0)

# Verificamos que ya no hay valores nulos en esas columnas
print("Valores vacíos restantes:")
print(df_fincas[['Area_Hectareas', 'Kilos_Recolectados']].isnull().sum())

Valores vacíos restantes:
Area_Hectareas        0
Kilos_Recolectados    0
dtype: int64

In [9]:
# Ejercicio 11: Transformación y Creación de Columnas con .apply()
# Definimos la función matemática
def calcular_rendimiento(fila):
    if fila['Area_Hectareas'] == 0:  # Prevenir división por cero
        return 0
    return fila['Kilos_Recolectados'] / fila['Area_Hectareas']

# Aplicamos la función para crear la nueva columna
df_fincas['Rendimiento_Kilos_Ha'] = df_fincas.apply(calcular_rendimiento, axis=1)

# Mostramos el resultado de la nueva columna
df_fincas[['ID_Finca', 'Area_Hectareas', 'Kilos_Recolectados', 'Rendimiento_Kilos_Ha']].head()

   ID_Finca  Area_Hectareas  Kilos_Recolectados  Rendimiento_Kilos_Ha
0  FIN-8001             3.0              4800.0           1600.000000
1  FIN-8002             5.5              2500.0            454.545455
2  FIN-8003             1.5              1200.0            800.000000
3  FIN-8004             3.0              4800.0           1600.000000
4  FIN-8005             8.0             16000.0           2000.000000

In [10]:
# Ejercicio 12: Renombrado y Reordenamiento de Atributos
# Renombramos usando un diccionario
df_fincas = df_fincas.rename(columns={'Metodo_Beneficio': 'Beneficio', 'Altitud_MSNM': 'Altitud'})

# Reorganizamos el orden de las columnas manualmente
columnas_ordenadas = ['ID_Finca', 'Rendimiento_Kilos_Ha', 'Municipio', 'Variedad', 
                      'Beneficio', 'Area_Hectareas', 'Kilos_Recolectados', 'Altitud', 'Certificacion']
df_fincas = df_fincas[columnas_ordenadas]

df_fincas.head()

,ID_Finca,Rendimiento_Kilos_Ha,Municipio,Variedad,Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud,Certificacion
0,FIN-8001,1600.000000,Chinchiná,Cenicafé 1,Honey,3.0,4800.0,1500,Ninguna
1,FIN-8002,454.545455,Manizales,Cenicafé 1,Natural,5.5,2500.0,1284,Rainforest Alliance
2,FIN-8003,800.000000,Manizales,Cenicafé 1,Lavado Tradicional,1.5,1200.0,1959,Rainforest Alliance
3,FIN-8004,1600.000000,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna
4,FIN-8005,2000.000000,Chinchiná,Castillo,Natural,8.0,16000.0,1929,Fairtrade

In [11]:
# Ejercicio 13: Agrupación y Métricas de Producción por Municipio
metricas_municipio = df_fincas.groupby('Municipio').agg({
    'Altitud': 'mean',
    'Kilos_Recolectados': 'sum'
})
print("--- MÉTRICAS POR MUNICIPIO ---")
print(metricas_municipio, "\n")

# Ejercicio 14: Dispersión con Función Personalizada (rango = max - min)
def rango(series):
    return series.max() - series.min()

dispersion_variedad = df_fincas.groupby('Variedad')[['Area_Hectareas', 'Kilos_Recolectados']].agg(rango)
print("--- DISPERSIÓN POR VARIEDAD (Rango) ---")
print(dispersion_variedad, "\n")

# Ejercicio 15: Agrupamiento Multinivel (Por Municipio y Variedad a la vez)
multinivel = df_fincas.groupby(['Municipio', 'Variedad']).agg({
    'Altitud': 'mean',
    'Kilos_Recolectados': 'sum'
})
print("--- AGRUPAMIENTO MULTINIVEL ---")
multinivel.head(10) # Mostramos solo las primeras 10 combinaciones

--- MÉTRICAS POR MUNICIPIO ---
               Altitud  Kilos_Recolectados
Municipio
Anserma    1637.025773            882900.0
Chinchiná  1625.582011            916700.0
Manizales  1637.788177            959600.0
Palestina  1638.493213           1111500.0
Risaralda  1647.020725            978700.0

--- DISPERSIÓN POR VARIEDAD (Rango) ---
               Area_Hectareas  Kilos_Recolectados
Variedad
Borbon Rosado            17.0             16000.0
Castillo                 17.0             16000.0
Cenicafé 1               17.0             16000.0
Colombia                 17.0             16000.0
Geisha                   17.0             16000.0

--- AGRUPAMIENTO MULTINIVEL ---

                             Altitud  Kilos_Recolectados
Municipio Variedad
Anserma   Borbon Rosado  1664.538462            177100.0
          Castillo       1587.000000            215300.0
          Cenicafé 1     1599.600000             85300.0
          Colombia       1645.613636            191000.0
          Geisha         1677.166667            214200.0
Chinchiná Borbon Rosado  1620.673469            255100.0
          Castillo       1651.000000            237200.0
          Cenicafé 1     1567.882353            172400.0
          Colombia       1691.500000            115000.0
          Geisha         1606.857143            137000.0